// Generated by CoffeeScript 1.9.2
this.BlogSummary = (function() {
  function BlogSummary() {}

  BlogSummary.prototype.start = function() {
    return $.ajax({
      url: "/payload.json",
      success: (function(_this) {
        return function(data) {
          _this.data = data;
          return _this.startSummary();
        };
      })(this)
    });
  };

  BlogSummary.prototype.startSummary = function() {
    var i, land, land_object, land_type, land_type_container, land_type_object, len, post, post_element, posts_container, ref, results;
    $("#content").html('<ul id="land-tree" class="summary"></ul>');
    ref = this.data["land_types"];
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      land_type = ref[i];
      land_type_object = $("<li>", {
        id: land_type.slug,
        "class": "summary-land-type"
      }).appendTo("#land-tree");
      $("<span>", {
        text: land_type.name,
        title: land_type.name
      }).appendTo(land_type_object);
      land_type_container = $("<ul>", {
        id: land_type.slug,
        "class": "summary-lands-container"
      }).appendTo(land_type_object);
      results.push((function() {
        var j, len1, ref1, results1;
        ref1 = this.data["lands"];
        results1 = [];
        for (j = 0, len1 = ref1.length; j < len1; j++) {
          land = ref1[j];
          if (land.type === land_type.slug) {
            land_object = $("<li>", {
              id: land.slug,
              "class": "summary-land"
            }).appendTo(land_type_container);
            $("<a>", {
              text: land.name,
              title: land.name,
              href: land.url
            }).appendTo(land_object);
            posts_container = $("<ul>", {
              "class": "summary-posts-container"
            }).appendTo(land_object);
            results1.push((function() {
              var k, len2, ref2, results2;
              ref2 = this.data["posts"];
              results2 = [];
              for (k = 0, len2 = ref2.length; k < len2; k++) {
                post = ref2[k];
                if (post.lands.indexOf(land.slug) >= 0) {
                  post_element = $("<li>", {
                    "class": "summary-post"
                  }).appendTo(posts_container);
                  results2.push($("<a>", {
                    text: post.date + " - " + post.title,
                    title: post.date + " - " + post.title,
                    href: post.url
                  }).appendTo(post_element));
                } else {
                  results2.push(void 0);
                }
              }
              return results2;
            }).call(this));
          } else {
            results1.push(void 0);
          }
        }
        return results1;
      }).call(this));
    }
    return results;
  };

  return BlogSummary;

})();
