# Site settings
title: Aleksander Kwiatkowski
header-ext-img: https://drscdn.500px.org/photo/76197267/m%3D2048/af7f0a557aa3f95ca5d3e595bd929832
email: aleksander_kwiatkowski1@interia.pl
description: "Short description of my trips in one place."
baseurl: ""
url: "http://http://akwiatkowski.homeio.org.pl/"
twitter_username: bobik314
github_username:  akwiatkowski
facebook_username:  bobik314

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
