# Site settings
title: OdkrywajacPolske.pl
header-ext-img: https://drscdn.500px.org/photo/136552853/m%3D2048/b2dd79b46cd3009b69c77c3f2811ca86
email: aleksander_kwiatkowski1@interia.pl
description: "Odkrywając rowerem i pieszo jaka Polska jest naprawdę"
baseurl: ""
url: "http://odkrywajacpolske.pl"
twitter_username: bobik314
github_username:  akwiatkowski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 6
paginate_path: "/list/page/:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
