# Site settings
title: Aleksander Kwiatkowski
header-ext-img: https://drscdn.500px.org/photo/98061073/m%3D2048/008b8fbb94a699cc547246e19fe80993
email: aleksander_kwiatkowski1@interia.pl
description: "Short description of my trips in one place."
baseurl: ""
url: "http://akwiatkowski.homeio.org.pl/"
twitter_username: bobik314
github_username:  akwiatkowski
facebook_username:  bobik314

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
