# Site settings
title: Aleksander Kwiatkowski
header-ext-img: https://drscdn.500px.org/photo/136552853/m%3D2048/b2dd79b46cd3009b69c77c3f2811ca86
email: aleksander_kwiatkowski1@interia.pl
description: "Krótki opis moich tras w jednym miejscu"
baseurl: ""
url: "http://akwiatkowski.homeio.org.pl/"
twitter_username: bobik314
github_username:  akwiatkowski
facebook_username:  bobik314

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/list/page/:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
