require "yaml"
require "../model/area_entity"
require "../model/photo_entity"

# Reads pre-computed photo-to-area assignments from YAML cache files.
# Cache is generated by commands/assign_photos_to_areas.cr using polygon-based matching.
class PhotoAreaCache
  Log = ::Log.for(self)

  @cache_path : String
  @photos_by_key : Hash(String, PhotoEntity)

  def initialize(@cache_path : String, @photos_by_key : Hash(String, PhotoEntity))
    Log.debug { "PhotoAreaCache initialized with #{@photos_by_key.size} photos, cache: #{@cache_path}" }
  end

  # Build a lookup hash from all posts' photos.
  # Key: "post_slug/filename" → PhotoEntity
  def self.build_lookup(posts : Array(Tremolite::Post)) : Hash(String, PhotoEntity)
    lookup = Hash(String, PhotoEntity).new
    posts.each do |post|
      post.published_photo_entities.each do |photo|
        key = "#{photo.post_slug}/#{photo.image_filename}"
        lookup[key] = photo
      end
    end
    lookup
  end

  # Get all cached photos for an area, resolved to PhotoEntity objects.
  # Returns empty array if cache file doesn't exist.
  def photos_for_area(area : AreaEntity) : Array(PhotoEntity)
    entries = read_cache_entries(area)
    resolve_entries(entries)
  end

  # Get top N photos for an area, sorted by points descending.
  def top_photos_for_area(area : AreaEntity, limit : Int32) : Array(PhotoEntity)
    photos = photos_for_area(area)
    photos.sort_by { |p| -p.points }.first(limit)
  end

  # Check if cache directory exists (indicates command has been run)
  def available? : Bool
    Dir.exists?(@cache_path)
  end

  private def read_cache_entries(area : AreaEntity) : Array({String, String})
    type_dir = area.area_type.english_plural
    path = File.join([@cache_path, type_dir, "#{area.slug}.yml"])

    return [] of {String, String} unless File.exists?(path)

    entries = [] of {String, String}
    yaml = YAML.parse(File.read(path))
    return entries unless yaml.raw.is_a?(Array)

    yaml.as_a.each do |entry|
      filename = entry["filename"]?.try(&.as_s) || next
      post_slug = entry["post_slug"]?.try(&.as_s) || next
      entries << {filename, post_slug}
    end
    entries
  end

  private def resolve_entries(entries : Array({String, String})) : Array(PhotoEntity)
    photos = [] of PhotoEntity
    entries.each do |filename, post_slug|
      key = "#{post_slug}/#{filename}"
      if photo = @photos_by_key[key]?
        photos << photo
      end
    end
    photos
  end
end
